name = "terminal"
license = "MIT"
description = ""
homepage = ""
tags = []
features = []
min_version = 0.57

[author]
  name = "panr"
  homepage = "https://radoslawkoziel.pl"
  twitter = "https://twitter.com/panr"
